[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
# Railway 会检查应用是否在分配的端口上响应
# healthcheckPath = "/health"
# healthcheckTimeout = 30

[env]
NODE_ENV = "production"
ENGINE = "google_free"
DEFAULT_TO_LANGS = "zh-CN,ja,ko,es,fr"
# 以下变量需要在 Railway 面板中设置
# OPENSUBTITLES_API_KEY = "your_key_here"
# GOOGLE_API_KEY = "your_key_here"  
# DEEPL_API_KEY = "your_key_here"

[[volumes]]
name = "subtitle-cache"
mountPath = "/usr/src/app/data"
