[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "npm start"

[env]
PORT = "3000"
BASE_URL = "https://your-app.up.railway.app"
ENGINE = "google_free"
DEFAULT_TO = "zh-CN"
# OPENSUBTITLES_API_KEY = "xxx"
# GOOGLE_API_KEY = "xxx"
# DEEPL_API_KEY = "xxx"

[[volumes]]
name = "subtitle-cache"
mountPath = "/usr/src/app/data"
