[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "npm start"

[env]
NODE_ENV = "production"
ENGINE = "google_free"
DEFAULT_TO_LANGS = "zh-CN,ja,ko,es,fr"

[[volumes]]
name = "subtitle-cache"
mountPath = "/usr/src/app/data"
